projects:
  botui:
    schemaPath: packages/api/src/graphql/schema.json
    includes:
      - packages/api/src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: packages/api/src/API.ts
        docsFilePath: packages/api/src/graphql
extensions:
  amplify:
    version: 3
