projects:
  BotuiAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - api/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: api/index.ts
        docsFilePath: src/graphql
        region: ap-northeast-1
        apiId: fteryxxs7rfljejtjer5g7qowi
        maxDepth: 2
extensions:
  amplify:
    version: 3
