version: '3'
services:
  next-server:
    build: .
    tty: true
    volumes:
      - ./:/app
      - /app/.next
      - node_modules_volume:/app/node_modules
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - 3000:3000
    working_dir: /app
volumes:
  node_modules_volume: