version: '3'
services:
  next-server:
    build: .
    tty: true
    volumes:
      - ./:/app
      - node_modules_volume:/app/node_modules
      - ~/.ssh/id_rsa.default:/root/.ssh/id_rsa
    ports:
      - 3000:3000
    working_dir: /app
    command: sh -c "yarn && yarn dev"
volumes:
  node_modules_volume: